import { useState, useRef, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Send, Bot, User, Loader2, Sparkles } from 'lucide-react';
import { toast } from 'sonner';
import type { AIMessage, GeneratedFile } from '@/types';

interface Props {
  projectId: string;
  model: string;
  messages: AIMessage[];
  setMessages: React.Dispatch<React.SetStateAction<AIMessage[]>>;
  onFilesGenerated: (files: GeneratedFile[], previewCode: string) => void;
}

export function BuilderChat({ projectId, model, messages, setMessages, onFilesGenerated }: Props) {
  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(false);
  const scrollRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: 'smooth' });
  }, [messages]);

  const handleSend = async () => {
    if (!input.trim() || loading) return;
    const userMsg: AIMessage = {
      id: crypto.randomUUID(),
      project_id: projectId,
      role: 'user',
      content: input.trim(),
      model,
      created_at: new Date().toISOString(),
    };
    setMessages((prev) => [...prev, userMsg]);
    setInput('');
    setLoading(true);

    // Simulate AI response — will be replaced with real edge function call
    setTimeout(() => {
      const demoFiles: GeneratedFile[] = [
        { path: 'src/App.tsx', content: `export default function App() {\n  return (\n    <div className="p-8">\n      <h1 className="text-3xl font-bold">${userMsg.content}</h1>\n      <p>Generated by Nexa One Builder</p>\n    </div>\n  );\n}`, language: 'tsx' },
        { path: 'src/main.tsx', content: `import React from 'react';\nimport ReactDOM from 'react-dom/client';\nimport App from './App';\n\nReactDOM.createRoot(document.getElementById('root')!).render(<App />);`, language: 'tsx' },
        { path: 'index.html', content: `<!DOCTYPE html>\n<html>\n<head><title>${userMsg.content}</title></head>\n<body><div id="root"></div><script type="module" src="/src/main.tsx"></script></body>\n</html>`, language: 'html' },
      ];

      const previewHtml = `<!DOCTYPE html><html><head><style>*{margin:0;font-family:system-ui}body{padding:2rem;background:#0a0a0f;color:#e2e8f0}h1{font-size:2rem;font-weight:700;margin-bottom:1rem;background:linear-gradient(135deg,#0ea5e9,#8b5cf6);-webkit-background-clip:text;-webkit-text-fill-color:transparent}p{color:#94a3b8}</style></head><body><h1>${userMsg.content}</h1><p>Generado por Nexa One Builder con modelo ${model}</p></body></html>`;

      const aiMsg: AIMessage = {
        id: crypto.randomUUID(),
        project_id: projectId,
        role: 'assistant',
        content: `He generado una aplicación basada en tu prompt. Se crearon ${demoFiles.length} archivos. Puedes ver el preview y editar por chat.`,
        model,
        created_at: new Date().toISOString(),
      };

      setMessages((prev) => [...prev, aiMsg]);
      onFilesGenerated(demoFiles, previewHtml);
      setLoading(false);
      toast.success('App generada exitosamente');
    }, 2000);
  };

  return (
    <div className="flex w-80 flex-col border-l border-border/50 bg-sidebar">
      <div className="flex items-center gap-2 border-b border-border/50 px-4 py-3">
        <Sparkles className="h-4 w-4 text-primary" />
        <span className="text-sm font-medium">Chat IA</span>
        <span className="ml-auto rounded bg-secondary px-1.5 py-0.5 text-xs text-muted-foreground">{model}</span>
      </div>

      <div ref={scrollRef} className="flex-1 overflow-y-auto p-3 space-y-3">
        {messages.length === 0 && (
          <div className="flex flex-col items-center justify-center py-12 text-center">
            <Bot className="mb-3 h-10 w-10 text-muted-foreground/30" />
            <p className="text-sm text-muted-foreground/60">Describe la app que quieres crear</p>
          </div>
        )}
        {messages.map((msg) => (
          <div key={msg.id} className={`flex gap-2 ${msg.role === 'user' ? 'justify-end' : ''}`}>
            {msg.role === 'assistant' && (
              <div className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-gradient-primary">
                <Bot className="h-3.5 w-3.5 text-primary-foreground" />
              </div>
            )}
            <div className={`max-w-[85%] rounded-xl px-3 py-2 text-sm ${
              msg.role === 'user'
                ? 'bg-primary text-primary-foreground'
                : 'bg-muted text-foreground'
            }`}>
              {msg.content}
            </div>
            {msg.role === 'user' && (
              <div className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-secondary">
                <User className="h-3.5 w-3.5" />
              </div>
            )}
          </div>
        ))}
        {loading && (
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <Loader2 className="h-4 w-4 animate-spin text-primary" />
            Generando...
          </div>
        )}
      </div>

      <div className="border-t border-border/50 p-3">
        <form onSubmit={(e) => { e.preventDefault(); handleSend(); }} className="flex gap-2">
          <Input value={input} onChange={(e) => setInput(e.target.value)}
            placeholder="Describe tu app..."
            className="flex-1 text-sm" disabled={loading} />
          <Button type="submit" size="icon" className="h-9 w-9 bg-gradient-primary hover:opacity-90" disabled={loading || !input.trim()}>
            <Send className="h-4 w-4" />
          </Button>
        </form>
      </div>
    </div>
  );
}
