import type { AIStructuredResponse } from './aiTypes';

// Provider interface — each provider implements this
export interface AIProviderAdapter {
  generate(prompt: string, context?: string): Promise<AIStructuredResponse>;
  edit(prompt: string, currentFiles: string, context?: string): Promise<AIStructuredResponse>;
}

// Placeholder implementations — will be replaced with real API calls via edge functions
function createPlaceholderProvider(name: string): AIProviderAdapter {
  return {
    async generate(prompt: string): Promise<AIStructuredResponse> {
      // This will be replaced by edge function calls
      return {
        projectName: prompt.slice(0, 30),
        description: `Generated by ${name}`,
        files: [
          {
            path: 'src/App.tsx',
            content: `export default function App() {\n  return (\n    <div className="p-8">\n      <h1 className="text-3xl font-bold">${prompt}</h1>\n      <p>Generated by ${name}</p>\n    </div>\n  );\n}`,
            language: 'tsx',
          },
          {
            path: 'src/main.tsx',
            content: `import React from 'react';\nimport ReactDOM from 'react-dom/client';\nimport App from './App';\n\nReactDOM.createRoot(document.getElementById('root')!).render(<App />);`,
            language: 'tsx',
          },
          {
            path: 'index.html',
            content: `<!DOCTYPE html>\n<html lang="en">\n<head><meta charset="UTF-8" /><title>${prompt}</title></head>\n<body><div id="root"></div><script type="module" src="/src/main.tsx"></script></body>\n</html>`,
            language: 'html',
          },
        ],
        dependencies: { react: '^18.3.0', 'react-dom': '^18.3.0' },
        pages: ['App'],
        components: ['App'],
      };
    },

    async edit(prompt: string, _currentFiles: string): Promise<AIStructuredResponse> {
      return this.generate(prompt);
    },
  };
}

export const openaiProvider = createPlaceholderProvider('OpenAI');
export const claudeProvider = createPlaceholderProvider('Claude');
export const geminiProvider = createPlaceholderProvider('Gemini');
export const customProvider = createPlaceholderProvider('Custom');
