// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { env } from '@/lib/env';

const SUPABASE_URL = env.SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = env.SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  // eslint-disable-next-line no-console
  console.error(
    '[supabase] Missing VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY at build time.',
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Use safe placeholder values when env is missing so the module load NEVER throws.
// Any actual API call will fail (auth flows surface the error in UI) but the React
// tree mounts successfully and the ErrorBoundary / Login screen can render.
const SAFE_URL = SUPABASE_URL || 'https://placeholder.supabase.co';
const SAFE_KEY = SUPABASE_PUBLISHABLE_KEY || 'placeholder-key';

export const supabase = createClient<Database>(SAFE_URL, SAFE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  },
});